In [1]:
import pandas as pd

In [2]:
data = {'name' : ['sudh' , 'krish' , 'hitesh' , 'tulesko'],
        'salary' : [100 , 200 , 300 , 400],
        'mail_id' : ['sudh@ineuron.ai' , 'krish@ineuron.ai' , 'hitesh@ineuron.ai' , 'tulesko@ineuron.ai'],
        'addr' : ['blr' , 'blr' , 'blr' , 'mum']
    }

In [30]:
df = pd.DataFrame(data)

In [31]:
df

name  salary             mail_id addr
0     sudh     100     sudh@ineuron.ai  blr
1    krish     200    krish@ineuron.ai  blr
2   hitesh     300   hitesh@ineuron.ai  blr
3  tulesko     400  tulesko@ineuron.ai  mum

In [32]:
df.loc[3:4]

name  salary             mail_id addr
3  tulesko     400  tulesko@ineuron.ai  mum

In [33]:
data1= {'pf_nu' : [234,45,54465,656],
        'income_tax' : [234,565,767,6778],
        'mobile_no' : [23543,43543,454,5656],
        'courses' : ['ds' , 'bigdata' , 'web dev ' , 'blockchian']
    
}

In [34]:
df1=pd.DataFrame(data1)

In [35]:
df

name  salary             mail_id addr
0     sudh     100     sudh@ineuron.ai  blr
1    krish     200    krish@ineuron.ai  blr
2   hitesh     300   hitesh@ineuron.ai  blr
3  tulesko     400  tulesko@ineuron.ai  mum

In [36]:
df1

pf_nu  income_tax  mobile_no     courses
0    234         234      23543          ds
1     45         565      43543     bigdata
2  54465         767        454    web dev 
3    656        6778       5656  blockchian

In [44]:
#Vertical concatination
pd.concat([df,df1])
#concat function helps to joi 2 dataset


name  salary             mail_id addr    pf_nu  income_tax  mobile_no  \
0     sudh   100.0     sudh@ineuron.ai  blr      NaN         NaN        NaN   
1    krish   200.0    krish@ineuron.ai  blr      NaN         NaN        NaN   
2   hitesh   300.0   hitesh@ineuron.ai  blr      NaN         NaN        NaN   
3  tulesko   400.0  tulesko@ineuron.ai  mum      NaN         NaN        NaN   
0      NaN     NaN                 NaN  NaN    234.0       234.0    23543.0   
1      NaN     NaN                 NaN  NaN     45.0       565.0    43543.0   
2      NaN     NaN                 NaN  NaN  54465.0       767.0      454.0   
3      NaN     NaN                 NaN  NaN    656.0      6778.0     5656.0   

      courses  
0         NaN  
1         NaN  
2         NaN  
3         NaN  
0          ds  
1     bigdata  
2    web dev   
3  blockchian

In [45]:
#Horiontal concatination
pd.concat([df,df1],axis=1)
#axis =1 means column wise contatination suppose to happen

name  salary             mail_id addr  pf_nu  income_tax  mobile_no  \
0     sudh     100     sudh@ineuron.ai  blr    234         234      23543   
1    krish     200    krish@ineuron.ai  blr     45         565      43543   
2   hitesh     300   hitesh@ineuron.ai  blr  54465         767        454   
3  tulesko     400  tulesko@ineuron.ai  mum    656        6778       5656   

      courses  
0          ds  
1     bigdata  
2    web dev   
3  blockchian

In [46]:
data2 = {'0' : ['sudh' , 'krish' , 'hitesh' , 'tulesko'],
        '1' : [100 , 200 , 300 , 400],
        '2' : ['sudh@ineuron.ai' , 'krish@ineuron.ai' , 'hitesh@ineuron.ai' , 'tulesko@ineuron.ai'],
        '3' : ['blr' , 'blr' , 'blr' , 'mum']
    }

In [64]:
data3= {'0' : [234,45,54465,656],
        '1' : [234,565,767,6778],
        '2' : [23543,43543,454,5656],
        '3' : ['ds' , 'bigdata' , 'web dev ' , 'blockchian']
    
}

In [65]:
df2 = pd.DataFrame(data2)

In [66]:
df3 = pd.DataFrame(data3)

In [67]:
pd.concat([df2,df3])

#here it's not showing any nan value because, both the data is having same header

0     1                   2           3
0     sudh   100     sudh@ineuron.ai         blr
1    krish   200    krish@ineuron.ai         blr
2   hitesh   300   hitesh@ineuron.ai         blr
3  tulesko   400  tulesko@ineuron.ai         mum
0      234   234               23543          ds
1       45   565               43543     bigdata
2    54465   767                 454    web dev 
3      656  6778                5656  blockchian

In [68]:
data4 = {'emp_id' : [101,102,103,104],
         'salary' : [234, 345,200,400],
         'pf' : [23,34,56,78],
         }

In [69]:
data5  = {'emp_id' : [101,102,104,105],
          'mob_no' : [3434,5656,767,878],
          'house_nu' : [345,345,345,56]
    
}

In [73]:
df4= pd.DataFrame(data4)

In [74]:
df5=pd.DataFrame(data5)

In [75]:
df4

emp_id  salary  pf
0     101     234  23
1     102     345  34
2     103     200  56
3     104     400  78

In [77]:
df5

emp_id  mob_no  house_nu
0     101    3434       345
1     102    5656       345
2     104     767       345
3     105     878        56

In [80]:
pd.merge(df4,df5,how="left")
#If we make" how="left"", than it will conside all the from left table and if we will make "how="rigt"" it will consider all the data from right

emp_id  salary  pf  mob_no  house_nu
0     101     234  23  3434.0     345.0
1     102     345  34  5656.0     345.0
2     103     200  56     NaN       NaN
3     104     400  78   767.0     345.0

In [82]:
pd.merge(df4,df5, how="right", on="emp_id")

emp_id  salary    pf  mob_no  house_nu
0     101   234.0  23.0    3434       345
1     102   345.0  34.0    5656       345
2     104   400.0  78.0     767       345
3     105     NaN   NaN     878        56

In [83]:
data6 = {'emp_id1' : [101,102,103,104],
         'salary' : [234, 345,200,400],
         'pf' : [23,34,56,78],
         }
         
data7  = {'emp_id2' : [101,102,104,105],
          'mob_no' : [3434,5656,767,878],
          'house_nu' : [345,345,345,56]
    
}

In [84]:
df6= pd.DataFrame(data6)

In [85]:
df7=pd.DataFrame(data7)

In [91]:
pd.merge(df6,df7,left_on="emp_id1",right_on="emp_id2",how='inner')

#There is no common header between df6 and df7. so we used the left_on and right_on to do the matching

emp_id1  salary  pf  emp_id2  mob_no  house_nu
0      101     234  23      101    3434       345
1      102     345  34      102    5656       345
2      104     400  78      104     767       345

In [92]:
data8 = {'emp_id' : [101,102,103,104],
         'salary' : [234, 345,200,400],
         'pf' : [23,34,56,78],
         }
         
data9  = {'emp_id' : [101,102,104,105,123],
          'salary' : [234, 345,200,878,43],
          'house_nu' : [345,345,345,56,234]
    
}

In [93]:
df8 = pd.DataFrame(data8)

In [94]:
df9 = pd.DataFrame(data9)

In [100]:
pd.merge(df8,df9,on=["salary","emp_id"])

emp_id  salary  pf  house_nu
0     101     234  23       345
1     102     345  34       345

In [101]:
data10 = {'emp_id1' : [101,102,103,104],
         'salary1' : [234, 345,200,400],
         'pf' : [23,34,56,78],
         }
         
data11  = {'emp_id2' : [101,102,104,105,123],
          'salary2' : [234, 345,200,878,43],
          'house_nu' : [345,345,345,56,234]
    
}

In [102]:
df10 = pd.DataFrame(data10,index=['a' ,'b','c' ,'d'])

In [103]:
df11 = pd.DataFrame(data11,index=['a','b','d','e','f'])

In [104]:
df10

emp_id1  salary1  pf
a      101      234  23
b      102      345  34
c      103      200  56
d      104      400  78

In [105]:
df11

emp_id2  salary2  house_nu
a      101      234       345
b      102      345       345
d      104      200       345
e      105      878        56
f      123       43       234

In [106]:
df10.join(df11)

emp_id1  salary1  pf  emp_id2  salary2  house_nu
a      101      234  23    101.0    234.0     345.0
b      102      345  34    102.0    345.0     345.0
c      103      200  56      NaN      NaN       NaN
d      104      400  78    104.0    200.0     345.0

In [114]:
df_sales=pd.read_csv(r"C:\Users\admin\Desktop\Ineuron\Dataset\sales_data_final.csv")

In [120]:
df_sales.head()

order_id order_date ship_date       ship_mode    customer_name  \
0     AG-2011-2040   1/1/2011  1/6/2011  Standard Class  Toby Braunhardt   
1    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   
2     HU-2011-1220   1/1/2011  1/5/2011    Second Class    Annie Thurman   
3  IT-2011-3647632   1/1/2011  1/5/2011    Second Class     Eugene Moren   
4    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   

       segment            state    country  market   region  ...  \
0     Consumer      Constantine    Algeria  Africa   Africa  ...   
1     Consumer  New South Wales  Australia    APAC  Oceania  ...   
2     Consumer         Budapest    Hungary    EMEA     EMEA  ...   
3  Home Office        Stockholm     Sweden      EU    North  ...   
4     Consumer  New South Wales  Australia    APAC  Oceania  ...   

          category sub_category                 product_name sales quantity  \
0  Office Supplies      Storage          Tenex Lockers, Blue   408        2   
1  Office Supplies     Supplies     Acme Trimmer, High Speed   120        3   
2  Office Supplies      Storage      Tenex Box, Single Width    66        4   
3  Office Supplies        Paper  Enermax Note Cards, Premium    45        3   
4        Furniture  Furnishings   Eldon Light Bulb, Duo Pack   114        5   

   discount   profit  shipping_cost  order_priority  year  
0       0.0  106.140          35.46          Medium  2011  
1       0.1   36.036           9.72          Medium  2011  
2       0.0   29.640           8.17            High  2011  
3       0.5  -26.055           4.82            High  2011  
4       0.1   37.770           4.70          Medium  2011  

[5 rows x 21 columns]

In [121]:
def profit_flag(a):
    if a>0:
        return("Positive")
    else:
        return ('Negative')
    

In [130]:
df_sales['flag_profit'] = df_sales['profit'].apply(profit_flag)
#It has created a new table and assign the "define" function into it

In [134]:
df_sales.head()

order_id order_date ship_date       ship_mode    customer_name  \
0     AG-2011-2040   1/1/2011  1/6/2011  Standard Class  Toby Braunhardt   
1    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   
2     HU-2011-1220   1/1/2011  1/5/2011    Second Class    Annie Thurman   
3  IT-2011-3647632   1/1/2011  1/5/2011    Second Class     Eugene Moren   
4    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   

       segment            state    country  market   region  ...  \
0     Consumer      Constantine    Algeria  Africa   Africa  ...   
1     Consumer  New South Wales  Australia    APAC  Oceania  ...   
2     Consumer         Budapest    Hungary    EMEA     EMEA  ...   
3  Home Office        Stockholm     Sweden      EU    North  ...   
4     Consumer  New South Wales  Australia    APAC  Oceania  ...   

                  product_name sales quantity discount   profit  \
0          Tenex Lockers, Blue   408        2      0.0  106.140   
1     Acme Trimmer, High Speed   120        3      0.1   36.036   
2      Tenex Box, Single Width    66        4      0.0   29.640   
3  Enermax Note Cards, Premium    45        3      0.5  -26.055   
4   Eldon Light Bulb, Duo Pack   114        5      0.1   37.770   

   shipping_cost  order_priority  year  flag_profit len_customer_name  
0          35.46          Medium  2011     Positive                15  
1           9.72          Medium  2011     Positive                11  
2           8.17            High  2011     Positive                13  
3           4.82            High  2011     Negative                12  
4           4.70          Medium  2011     Positive                11  

[5 rows x 23 columns]

In [133]:
df_sales["len_customer_name"]=df_sales['customer_name'].apply(len)

In [136]:
def quantity_flag(a):
    if a <10:
        return 'Low'
    elif a>10 and a<20:
        return "Medium"
    else:
        return "High"

In [137]:
df_sales["quantity_flag"]= df_sales["quantity"].apply(quantity_flag)

In [139]:
df_sales.head()

order_id order_date ship_date       ship_mode    customer_name  \
0     AG-2011-2040   1/1/2011  1/6/2011  Standard Class  Toby Braunhardt   
1    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   
2     HU-2011-1220   1/1/2011  1/5/2011    Second Class    Annie Thurman   
3  IT-2011-3647632   1/1/2011  1/5/2011    Second Class     Eugene Moren   
4    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   

       segment            state    country  market   region  ... sales  \
0     Consumer      Constantine    Algeria  Africa   Africa  ...   408   
1     Consumer  New South Wales  Australia    APAC  Oceania  ...   120   
2     Consumer         Budapest    Hungary    EMEA     EMEA  ...    66   
3  Home Office        Stockholm     Sweden      EU    North  ...    45   
4     Consumer  New South Wales  Australia    APAC  Oceania  ...   114   

  quantity discount   profit shipping_cost  order_priority  year  flag_profit  \
0        2      0.0  106.140         35.46          Medium  2011     Positive   
1        3      0.1   36.036          9.72          Medium  2011     Positive   
2        4      0.0   29.640          8.17            High  2011     Positive   
3        3      0.5  -26.055          4.82            High  2011     Negative   
4        5      0.1   37.770          4.70          Medium  2011     Positive   

   len_customer_name quantity_flag  
0                 15           Low  
1                 11           Low  
2                 13           Low  
3                 12           Low  
4                 11           Low  

[5 rows x 24 columns]

In [144]:
df_sales['square_quantity'] =df_sales["quantity"].apply(lambda a : a*2)
#By using lamda funtion use square of quantity

In [143]:
df_sales.head(10)

order_id order_date ship_date       ship_mode     customer_name  \
0     AG-2011-2040   1/1/2011  1/6/2011  Standard Class   Toby Braunhardt   
1    IN-2011-47883   1/1/2011  1/8/2011  Standard Class       Joseph Holt   
2     HU-2011-1220   1/1/2011  1/5/2011    Second Class     Annie Thurman   
3  IT-2011-3647632   1/1/2011  1/5/2011    Second Class      Eugene Moren   
4    IN-2011-47883   1/1/2011  1/8/2011  Standard Class       Joseph Holt   
5    IN-2011-47883   1/1/2011  1/8/2011  Standard Class       Joseph Holt   
6     CA-2011-1510   1/2/2011  1/6/2011  Standard Class   Magdelene Morse   
7    IN-2011-79397   1/3/2011  1/3/2011        Same Day       Kean Nguyen   
8    ID-2011-80230   1/3/2011  1/9/2011  Standard Class      Ken Lonsdale   
9     IZ-2011-4680   1/3/2011  1/7/2011  Standard Class  Lindsay Williams   

       segment            state      country  market   region  ... quantity  \
0     Consumer      Constantine      Algeria  Africa   Africa  ...        2   
1     Consumer  New South Wales    Australia    APAC  Oceania  ...        3   
2     Consumer         Budapest      Hungary    EMEA     EMEA  ...        4   
3  Home Office        Stockholm       Sweden      EU    North  ...        3   
4     Consumer  New South Wales    Australia    APAC  Oceania  ...        5   
5     Consumer  New South Wales    Australia    APAC  Oceania  ...        2   
6     Consumer          Ontario       Canada  Canada   Canada  ...        1   
7    Corporate  New South Wales    Australia    APAC  Oceania  ...        1   
8     Consumer         Auckland  New Zealand    APAC  Oceania  ...        4   
9    Corporate           Ninawa         Iraq    EMEA     EMEA  ...        4   

  discount   profit shipping_cost order_priority  year  flag_profit  \
0      0.0  106.140         35.46         Medium  2011     Positive   
1      0.1   36.036          9.72         Medium  2011     Positive   
2      0.0   29.640          8.17           High  2011     Positive   
3      0.5  -26.055          4.82           High  2011     Negative   
4      0.1   37.770          4.70         Medium  2011     Positive   
5      0.1   15.342          1.80         Medium  2011     Positive   
6      0.0    3.120         24.10         Medium  2011     Positive   
7      0.1  110.412        125.32       Critical  2011     Positive   
8      0.4 -319.464        107.10            Low  2011     Negative   
9      0.0  253.320         81.26           High  2011     Positive   

   len_customer_name  quantity_flag square_quantity  
0                 15            Low               4  
1                 11            Low               6  
2                 13            Low               8  
3                 12            Low               6  
4                 11            Low              10  
5                 11            Low               4  
6                 15            Low               2  
7                 11            Low               2  
8                 12            Low               8  
9                 16            Low               8  

[10 rows x 25 columns]

In [145]:
import numpy as np

In [146]:
np.array([2,3,4,5,6])

array([2, 3, 4, 5, 6])

In [155]:
type(np.array([2,3,4,5,6]))
#This is an one dimensional array

numpy.ndarray

In [156]:
np.array([[2,3,4] , [4,5,6]])
#This is an two dimensional array

array([[2, 3, 4],
       [4, 5, 6]])

In [153]:
type(np.array([[2,3,4] , [4,5,6]]))

numpy.ndarray

In [159]:
a = np.array([3,4,5,6] , ndmin= 3)
#ndim functions helps to define the array. here ndim=3, so it will create a 3 dimensional array

In [160]:
a

array([[[3, 4, 5, 6]]])

In [161]:
arr = np.array([[1,2,3] , [4,5,6] , [7,8,9]])

In [162]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [164]:
arr.ndim
#ndim will show thw number of arrays

2

In [166]:
np.random.randint(1,10,(4,4))
#randint(1,10(4,4))== This will help to give random integer number between 1 to 10 with 4 rows and 4 column dimension.

array([[1, 1, 6, 6],
       [6, 8, 5, 3],
       [2, 6, 4, 5],
       [3, 8, 5, 1]])

In [167]:
np.random.randint(1,10,(4,4,2))

array([[[7, 8],
        [7, 9],
        [9, 8],
        [6, 9]],

       [[1, 5],
        [7, 3],
        [1, 4],
        [3, 1]],

       [[2, 2],
        [6, 6],
        [8, 9],
        [8, 4]],

       [[9, 2],
        [9, 6],
        [3, 1],
        [2, 3]]])